branch-defaults:
  main:
    environment: Gotutorial-env
environment-defaults:
  Gotutorial-env:
    branch: null
    repository: null
global:
  application_name: go_tutorial
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
